CREATE table if not EXISTS aluno(
  cgm integer PRIMARY KEY  NOT null UNIQUE,
  nome varchar (400) not NULL,
  nascimento date not NULL, 
  cpf_aluno varchar (11) not NULL UNIQUE,
  rg varchar (9) NOT NULL unique,
  genero text,
  email_aluno varchar (800),
  telefone_aluno varchar (15),
  endereço varchar (500),
  cep varchar (9),
  numero integer,
  complemento varchar (200),
  bairro varchar (100),
  cidade varchar (250),
  estado varchar (150),
  curso varchar (50) not null ,
  turno varchar (20) NOT NULL,
  turma varchar (10) not NULL,
  responsavel varchar (500),
  grau_parentesco varchar (40),
  cpf_responsavel varchar (11) not NULL UNIQUE,
  telefone_responsavel varchar (15),
  email_responsavel varchar (800),
  id_fo integer,
  FOREIGN key (id_fo) REFERENCES fo (id_fo)
  );
