CREATE TABLE IF NOT EXISTS aluno (
  id_aluno INTEGER PRIMARY KEY AUTOINCREMENT,
  cgm INTEGER NOT NULL UNIQUE,
  nome VARCHAR(400) NOT NULL,
  nascimento DATE NOT NULL, 
  cpf_aluno VARCHAR(11) NOT NULL UNIQUE,
  rg VARCHAR(9) NOT NULL UNIQUE,
  genero TEXT,
  email_aluno VARCHAR(800),
  telefone_aluno VARCHAR(15),
  endereco VARCHAR(500),
  cep VARCHAR(9),
  numero INTEGER,
  complemento VARCHAR(200),
  bairro VARCHAR(100),
  cidade VARCHAR(250),
  estado VARCHAR(150),
  curso VARCHAR(50) NOT NULL,
  turno VARCHAR(20) NOT NULL,
  turma VARCHAR(10) NOT NULL,
  id_responsavel INTEGER NOT NULL,
  id_frequencia INTEGER,
  id_fo INTEGER,
  FOREIGN KEY (id_responsavel) REFERENCES responsavel (id_responsavel),
  FOREIGN KEY (id_frequencia) REFERENCES frequencias (id_frequencia),
  FOREIGN KEY (id_fo) REFERENCES fo (id_fo)
);
