CREATE table if not EXISTS funcionario(
  nome VARCHAR(100) NOT NULL,
  cpf VARCHAR(14) NOT NULL UNIQUE PRIMARY key,
  nascimento date not null,
  rg varchar (16) not null,
  genero text,
  estado_civil text,
  email text,
  email_institucional text,
  telefone VARCHAR(15)NOT NULL UNIQUE,
  telefone_alternativo VARCHAR(15)NOT NULL,
  cep varchar (9),
  numero integer,
  complemento varchar (200),
  bairro varchar (100),
  cidade varchar (250),
  estado varchar (150),
  data_adimição DATE NOT NULL,
  cargo varchar (500),
  carga_horaria integer,
  contrato varchar (80),
  numero_registro integer,
  id  INTEGER,
  FOREIGN KEY (id) REFERENCES funcao(id)
  );
